### ISSUE TITLE
Bind scroll listener to something other than window

### ISSUE THREAD

**Issue by joan-artimedia** [nateplusplus/pushin#162]
Hello!
I'm trying to implement this plugin in a modal. I would like to control the animation with the scroll inside the modal. Is this possible?
Cheers

**Comment by nateplusplus** [comment]
@joan-artimedia Thanks for reaching out! There is no easy way to do this at the moment, but I will certainly consider this for an upcoming release because I can definitely see the value in it.

As you've mentioned, window events are pretty interwoven into the core functionality of this plugin so I don't have any good suggestions for a temporary workaround. If you are up to the challenge, feel free to submit a PR and I will work with you on it.

**Comment by nateplusplus** [comment]
@joan-artimedia - Quick update: I've made progress on this feature, and I plan to merge it with the next major release. There are a few other things I am planning on adding with that release so I will keep you posted once it's available.

Please let me know if you need this feature more immediately and I will sort something out for you.

**Comment by joan-artimedia** [comment]
@nateplusplus we figured out a hacky way of implementing what we wanted, it's not the best but it works for us. Thanks so much for the update though, I'm sure it'll help people in the future.

**Comment by nateplusplus** [comment]
@joan-artimedia This feature is now included in the newest release, v5.0.0. Here is some documentation you can follow to attach this effect to any container on your page: [https://nateplusplus.github.io/pushin/target/](https://nateplusplus.github.io/pushin/target/)

If you have any more feedback, ideas or issues, I would love to hear them. Thanks again!

Closing this issue.
