### ISSUE TITLE
Future improvements

### ISSUE THREAD

**Issue by arturovt** [nateplusplus/pushin#78]
- [x] #80
- [x] #81
- [x] ensure this package is compatible with Node.js and can be loaded on the server-side w/o exceptions. This is important for applications using server-side rendering. We use browser API that's not available on the Node.js side, e.g. accessing `window` directly will throw an exception `window is not defined`. This is achieved by checking if those APIs are defined or not, e.g.:
```js
if (typeof window !== 'undefined') window.addEventListener(...);
```
- [x] we need to ensure that we share global event listeners between multiple instances, e.g. `window.onresize`

**Comment by nateplusplus** [comment]
@arturovt - great points! I have made the first two into separate issues.

I agree with the window global issue as well. On the other hand, we do need to know the size of the viewport to render things in the correct position on page load. Perhaps the simplest solution would be to keep elements hidden until there is a viewport? I'm not sure the best solution here. Any thoughts?

**Comment by nateplusplus** [comment]
As of v4.0.2, this package does not throw errors when run in a node environment. I have included instructions for binding events once a client window is available since this code is dependent on client-side events.

I believe all requirements of this issue are satisfied. If you have ideas for further improvements please open a new issue to continue the conversation.
